kind: pipeline
type: ssh
name: deployment

server:
  host:
    from_secret: host
  user:
    from_secret: user
  password:
    from_secret: password

clone:
  disable: true

steps:
  - name: move
    commands:
      - cd /home/apper/projects/betaaloverzicht-api
      - git checkout main
      - git pull
      - docker-compose -f docker-compose.prod.yml up -d --build
      - ./migrate.sh docker-compose.prod.yml

trigger:
  branch:
    - main
  event:
    - push
