version: "3.8"
services:
  db:
    image: postgres:14.1
    volumes:
      - db-data:/data/betaaloverzicht
      - "./postgresql.conf:/var/lib/postgresql/data/postgresql.conf"
    ports:
      - "3333:5432"
    env_file: .env

  api:
    image: postgrest/postgrest
    ports:
      - "2222:3000"
    depends_on:
      - db
    env_file: .env
    volumes:
      - "./certs/:/opt/config/"

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "1111:8080"
    env_file: .env

volumes:
  db-data:
